version: '3'

services:

  rabbitmq:
    image: 'rabbitmq:3.8-management-alpine'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - network

  job-api:
    build: job-api
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: 'rabbitmq'
    ports:
      - 8080:8080
    networks:
      - network

  worker:
    build: worker
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: 'rabbitmq'
      JOBS_API_HOST: 'http://job-api:8080'
    networks:
      - network

networks:
  network: {}